# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-31 14:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_data', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('User_ID', models.CharField(blank=True, max_length=100, null=True, verbose_name='用户ID')),
                ('Merchant_ID', models.CharField(blank=True, max_length=100, verbose_name='商家ID')),
            ],
            options={
                'db_table': '订单',
            },
        ),
        migrations.CreateModel(
            name='product_single',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.IntegerField(verbose_name='条形码')),
                ('product_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='商品名称')),
                ('User_ID', models.CharField(blank=True, max_length=100, null=True, verbose_name='用户ID')),
                ('Merchant_ID', models.CharField(blank=True, max_length=100, verbose_name='商家ID')),
                ('price', models.FloatField(null=True, verbose_name='单价')),
                ('num', models.IntegerField(default=0, verbose_name='数量')),
                ('create_data', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('order_num', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='CheckOut.order', verbose_name='订单号')),
            ],
            options={
                'db_table': '商品流水单',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=100, verbose_name='用户名')),
                ('avatar', models.ImageField(blank=True, default='avatar/default.png', max_length=200, null=True, upload_to='avatar/%Y/%m', verbose_name='用户头像')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='邮箱')),
                ('mobile', models.CharField(blank=True, max_length=11, null=True, verbose_name='手机号')),
            ],
        ),
    ]
