# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-31 15:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('CheckOut', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('FD', 'Finished'), ('TO', 'TimeOut'), ('PF', 'PayFailed'), ('NL', 'Normal')], default=django.utils.timezone.now, max_length=5, verbose_name='订单状态'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='user_category',
            field=models.CharField(choices=[('M', 'Merchant'), ('C', 'Customer'), ('T', 'Terminal'), ('A', 'Staff')], default=datetime.datetime(2016, 12, 31, 15, 17, 18, 846342, tzinfo=utc), max_length=1, verbose_name='用户类型'),
            preserve_default=False,
        ),
    ]
