# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-31 15:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CheckOut', '0002_auto_20161231_2317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_name',
            new_name='username',
        ),
    ]
