# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CheckOut', '0003_auto_20161231_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, max_length=20, verbose_name='密码'),
        ),
    ]
