# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 12:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('CheckOut', '0004_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='regist_data',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='user_category',
            field=models.CharField(choices=[('M', 'Merchant'), ('C', 'Customer'), ('T', 'Terminal'), ('A', 'Staff')], default='C', max_length=1, verbose_name='用户类型'),
        ),
    ]
