# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 10:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CheckOut', '0005_auto_20170103_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_single',
            name='order_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CheckOut.order', verbose_name='订单号'),
        ),
    ]
