# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-11 01:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CheckOut', '0006_auto_20170104_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='User_ID',
            field=models.CharField(blank=True, default='-', max_length=100, null=True, verbose_name='用户ID'),
        ),
        migrations.AlterField(
            model_name='product_single',
            name='price',
            field=models.FloatField(default=0, null=True, verbose_name='单价'),
        ),
        migrations.AlterField(
            model_name='product_single',
            name='product_name',
            field=models.CharField(blank=True, default='-', max_length=100, null=True, verbose_name='商品名称'),
        ),
    ]
