# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-11 01:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CheckOut', '0007_auto_20170111_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_single',
            name='User_ID',
            field=models.CharField(blank=True, default='-', max_length=100, null=True, verbose_name='用户ID'),
        ),
    ]
